CREATE SCHEMA IF NOT EXISTS INVENTORY;

CREATE TABLE IF NOT EXISTS INVENTORY.FRANCHISE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INVENTORY.BRANCH (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FRANCHISE BIGINT NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BRANCH_FRANCHISE
        FOREIGN KEY (ID_FRANCHISE)
        REFERENCES INVENTORY.FRANCHISE (ID)
        ON DELETE RESTRICT,
    CONSTRAINT UQ_BRANCH_PER_FRANCHISE
        UNIQUE (ID_FRANCHISE, NAME)
);

CREATE TABLE IF NOT EXISTS INVENTORY.PRODUCT (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_BRANCH BIGINT NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    STOCK_QUANTITY INTEGER NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRODUCT_BRANCH
        FOREIGN KEY (ID_BRANCH)
        REFERENCES INVENTORY.BRANCH (ID)
        ON DELETE CASCADE,
    CONSTRAINT UQ_PRODUCT_PER_BRANCH
        UNIQUE (ID_BRANCH, NAME),
    CONSTRAINT CK_STOCK_QUANTITY_NON_NEGATIVE
        CHECK (STOCK_QUANTITY >= 0)
);

CREATE INDEX IF NOT EXISTS IDX_BRANCH_ID_FRANCHISE ON INVENTORY.BRANCH (ID_FRANCHISE);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_ID_BRANCH ON INVENTORY.PRODUCT (ID_BRANCH);
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_NAME ON INVENTORY.PRODUCT (NAME);
